### ISSUE TITLE
Add possibility to group layers to the TOC

### ISSUE THREAD

**Issue by pascalhorton** [terranum-ch/ToolMap#467] opened 2022-03-18 11:51 UTC
**Objective**: The creation of layer groups in the TOC will allow to show or hide several layers simultaneously. 
**Technical details**: To display groups of layers, it will be necessary to change the visual controller of the TOC to a more elaborate treeview. This involves a complete redesign of this aspect of the interface, the drag and drop behavior, as well as the logic of loading and saving the TOC. It will also be necessary to modify the table containing the properties of the TOC in the database in order to store the properties of the groups, and the membership relations of the different layers. The management of groups in the TOC will also have to be implemented, as well as the addition and removal of groups. When a group is deleted, the layers should be associated with the parent group or the root of the TOC. Any changes to these groups should be recorded immediately in the project.

**Comment by lucsch** [comment] 2022-09-27 09:19
duplicate of #477

**Closed by lucsch** 2022-09-27 09:19 UTC
Labels: duplicate, enhancement
